# Generated by Django 4.2.2 on 2023-06-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images')),
                ('keyword', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
